/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f429xx.h"

// Prototipos de funciones
void SystemClock_Config(void);
void GPIO_Init(void);
void Delay(uint32_t count);

int main(void)
{
    uint32_t salida = 0;

    uint32_t PB0 = 0, PB7=0, PB14=0,PB11 = 0, PB10=0;

    uint32_t PE7 = 0, PE8=0, PE10=0, PE12=0, PE14=0, PE15=0;

    SystemClock_Config();
    GPIO_Init();

    while (1)
    {
       if((GPIOC->IDR & GPIO_IDR_ID13) == 0)
       {
            PB0 ^= (0x00000001);
       }
       else
       {
            PB14 ^= (0x00004000);
       }

       salida ^= 0xAA;

		PB11 = (salida & 0x80) << 0x04; // LED7 - PB11
		PB10 = (salida & 0x40) << 0x04; // LED6 - PB10
		PE15 = (salida & 0x20) << 0x0A; // LED5 - PE15
		PE14 = (salida & 0x10) << 0x0A; // LED4 - PE14
		PE12 = (salida & 0x08) << 0x09; // LED3 - PE12
		PE10 = (salida & 0x04) << 0x08; // LED2 - PE10
		PE7  = (salida & 0x02) << 0x06; // LED1 - PE7
		PE8  = (salida & 0x01) << 0x08; // LED0 - PE8

		GPIOB->ODR = PB14 + PB11 + PB10 + PB7 + PB0 ; // LED1 - PB0
		GPIOE->ODR = PE15 + PE14 + PE12 + PE10 + PE7 + PE8 ; // LEDs - PE15, PE14, PE12, PE10, PE7, PE8

		Delay(500000);

    }
}

void GPIO_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
    (void)RCC->AHB1ENR;

    // LED1 - PB0 salida
    GPIOB->MODER &= ~(3);
    GPIOB->MODER |=  (1);

    // LED2 - PB7 salida
    GPIOB->MODER &= ~(0x0000C000);
    GPIOB->MODER |=  (0x00004000);

    // LED3 - PB14 salida
    GPIOB->MODER &= ~(0x30000000);
    GPIOB->MODER |=  (0x10000000);

    // SW1 - PC13 Entrada
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
    (void)RCC->AHB1ENR;

    GPIOC->MODER &= ~(0xC0000000);
    GPIOC->MODER |=  (0x00000000);

    // Configurar el puerto GPIOB
    // PB11    PB10
    // LED7    LED6

    GPIOB->MODER &= ~(3 << (22)); // Limpiar los bits de modo para PB11
    GPIOB->MODER |=  (1 << (22));

     GPIOB->MODER &= ~(3 << (20)); // Limpiar los bits de modo para PB10
    GPIOB->MODER |=  (1 << (20));

    // Configurar el puerto GPIOE
    // PE15 PE14 PE13 PE12 PE11 PE10 PE9 PE8  PE7
    // LED5 LED4 SW4  LED3 SW2  LED2 SW1 LED0 LED1

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
    (void)RCC->AHB1ENR;

    GPIOE->MODER &= ~(0xFFFFC000);
    GPIOE->MODER |=  (0x51514000);


    // Configurar PE15 como salida
    GPIOE->MODER &= ~(3 << (30));
    GPIOE->MODER |=  (1 << (30));

    // Configurar PE14 como salida
    GPIOE->MODER &= ~(3 << (28));
    GPIOE->MODER |=  (1 << (28));

    // Configurar PE13 como entrada
    GPIOE->MODER &= ~(3 << (26));
    GPIOE->MODER |=  (0 << (26));

    // Configurar PE12 como salida
    GPIOE->MODER &= ~(3 << (24));
    GPIOE->MODER |=  (1 << (24));

    // Configurar PE11 como entrada
    GPIOE->MODER &= ~(3 << (22));
    GPIOE->MODER |=  (0 << (22));

    // Configurar PE10 como salida
    GPIOE->MODER &= ~(3 << (20));
    GPIOE->MODER |=  (1 << (20));

    // Configurar PE9 como entrada
    GPIOE->MODER &= ~(3 << (18));
    GPIOE->MODER |=  (0 << (18));

    // Configurar PE8 como salida
    GPIOE->MODER &= ~(3 << (16));
    GPIOE->MODER |=  (1 << (16));

    // Configurar PE7 como salida
    GPIOE->MODER &= ~(3 << (14));
    GPIOE->MODER |=  (1 << (14));

    // Configurar el puerto GPIOF
    // PF15 PF14 PF13
    // SW5  SW3 SW0

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
    (void)RCC->AHB1ENR;

    // Configurar PF15 como entrada
    GPIOF->MODER &= ~(3 << (30));
    GPIOF->MODER |=  (0 << (30));

    // Configurar PF14 como entrada
    GPIOF->MODER &= ~(3 << (28));
    GPIOF->MODER |=  (0 << (28));

    // Configurar PF13 como entrada
    GPIOF->MODER &= ~(3 << (26));
    GPIOF->MODER |=  (0 << (26));

    // Configurar el puerto GPIOG
    // PG14 PG9
    // SW6  SW7

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;
    (void)RCC->AHB1ENR;

    // Configurar PG14 como entrada
    GPIOG->MODER &= ~(3 << (28));
    GPIOG->MODER |=  (0 << (28));

    // Configurar PG9 como entrada
    GPIOG->MODER &= ~(3 << (18));
    GPIOG->MODER |=  (0 << (18));

}

void SystemClock_Config(void)
{
    RCC->CR |= RCC_CR_HSION;
    while(!(RCC->CR & RCC_CR_HSIRDY));

    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_HSI;
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);
}

void Delay(uint32_t count)
{
    volatile uint32_t i;
    for (i = 0; i < count; i++)
    {
        __NOP();
    }
}
