/********************************************************************************
* @file : main.c
* @author : Auto-generated by STM32CubeIDE
* @brief : Main program body

******************************************************************************

* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************

*/

#include "stm32f429xx.h"

// Prototipos de funciones

void SystemClock_Config(void);
void GPIO_Init(void);
void Delay(uint32_t count);
void salida_leds(uint32_t leds);
void salida_display(uint32_t leds);
void board_leds(uint32_t leds);
uint32_t deco_display(uint32_t numero);
uint32_t entrada_sw(void);

int main(void)
{
	uint32_t Leds = 0;
	uint32_t contador = 0;

	SystemClock_Config();
	GPIO_Init();

	while (1)
	{

		if((GPIOC->IDR & GPIO_IDR_ID13) == 0)
		{
			Leds ^= 0x02;
			Leds &= ~(0x04);
			board_leds(Leds);
		}
		else
		{
			Leds ^= 0x04;
			Leds &= ~(0x02);
			board_leds(Leds);
		}

		salida_leds(entrada_sw());

        GPIOF->ODR |=  (1 << 12);// DO - PF12 salida
        GPIOD->ODR &= ~(1 << 15);// D1 - PD15 salida
        GPIOD->ODR &= ~(1 << 14);// D2 - PD14 salida
        GPIOA->ODR &= ~(1 <<  7);// D3 - PDA7 salida

        salida_display(deco_display(1));
    	Delay(5000);

        GPIOF->ODR &= ~(1 << 12);// DO - PF12 salida
        GPIOD->ODR |=  (1 << 15);// D1 - PD15 salida
        GPIOD->ODR &= ~(1 << 14);// D2 - PD14 salida
        GPIOA->ODR &= ~(1 <<  7);// D3 - PDA7 salida

        salida_display(deco_display(2));
        Delay(5000);

        contador += 1;

        if (contador > 9)
        {
        	 contador = 0;
        }



	}

}

uint32_t deco_display(uint32_t numero)
{
	if(numero == 0) 	 return 0xBF; // 0
	else if(numero == 1) return 0x86; // 1
	else if(numero == 2) return 0xDB; // 2
	else if(numero == 3) return 0xCF; // 3
	else if(numero == 4) return 0xE6; // 4
	else if(numero == 5) return 0xED; // 5
	else if(numero == 6) return 0xFD; // 6
	else if(numero == 7) return 0x87; // 7
	else if(numero == 8) return 0xFF; // 8
	else if(numero == 9) return 0xEF; // 9

}

void salida_display(uint32_t display)
{
    uint32_t SA = 0, SB = 0, SC = 0, SD = 0;
    uint32_t SE = 0, SF = 0, SG = 0, DP = 0;

	DP = (display & 0x80) >> 0x06; // DP7 - PB1
	SG = (display & 0x40) >> 0x04; // SG6 - PC2
	SF = (display & 0x20) << 0x07; // SF5 - PD12
	SE = (display & 0x10) >> 0x02; // SE4 - PB2
	SD = (display & 0x08) << 0x03; // SD3 - PB6
	SC = (display & 0x04) << 0x02; // SC2 - PF4
	SB = (display & 0x02) << 0x0C; // SB1 - PD13
	SA = (display & 0x01) << 0x0B; // SA0 - PD11

	GPIOB->ODR &= ~((1 << 1) + (1 << 2) + (1 << 6));
	GPIOB->ODR |= DP + SE + SD; // PB1 - PB2, PB6

    GPIOC->ODR &= ~((1 << 2));
	GPIOC->ODR |= SG; // PC2

	GPIOD->ODR &= ~((1 << 11) + (1 << 12) + (1 << 13));
	GPIOD->ODR |= SA + SB + SF ; // PD11, PD12, PD13

    GPIOF->ODR &= ~((1 << 4));
	GPIOF->ODR |= SC; // PF4
}


uint32_t entrada_sw(void)
{

	uint32_t entrada=0;
	uint32_t PF13 = 0, PE9=0, PE11=0, PF14 = 0;
	uint32_t PE13 = 0, PF15=0, PG14=0, PG9 = 0;

	PF13 = (GPIOF->IDR & GPIO_IDR_ID13) >> 13; 	// PF13 - SW0
	 PE9 = (GPIOE->IDR &  GPIO_IDR_ID9) >>  8; 	// PE9 - SW1
	PE11 = (GPIOE->IDR & GPIO_IDR_ID11) >>  9; 	// PE11 - SW2
	PF14 = (GPIOF->IDR & GPIO_IDR_ID14) >> 11; 	// PF14 - SW3
	PE13 = (GPIOE->IDR & GPIO_IDR_ID13) >>  9; 	// PE13 - SW4
	PF15 = (GPIOF->IDR & GPIO_IDR_ID15) >> 10; 	// PF15 - SW5
	PG14 = (GPIOG->IDR & GPIO_IDR_ID14) >>  8; 	// PF14 - SW6
	 PG9 = (GPIOG->IDR &  GPIO_IDR_ID9) >>  2; 	// PG9 - SW7

	entrada = PF13 + PE9 + PE11 + PF14 + PE13 + PF15 + PG14 + PG9;
	return entrada;

}

void board_leds(uint32_t leds)
{
	uint32_t PB0 = 0, PB7=0, PB14=0;

	PB14 = (leds & 0x04) << 0x0C; 	// LD2 - PB14
	 PB7 = (leds & 0x02) << 0x06; 	// LD1 - PB7
	 PB0 = (leds & 0x01) << 0x00; 	// LD0 - PB0

	GPIOB->ODR &= ~((1 << 0) + (1 << 7) + (1 << 14));
	GPIOB->ODR |= PB14 + PB7 + PB0;

}


void salida_leds(uint32_t leds)
{

	uint32_t PB11 = 0, PB10=0;
	uint32_t PE7 = 0, PE8=0, PE10=0, PE12=0, PE14=0, PE15=0;

	PB11 = (leds & 0x80) << 0x04; // LED7 - PB11
	PB10 = (leds & 0x40) << 0x04; // LED6 - PB10
	PE15 = (leds & 0x20) << 0x0A; // LED5 - PE15
	PE14 = (leds & 0x10) << 0x0A; // LED4 - PE14
	PE12 = (leds & 0x08) << 0x09; // LED3 - PE12
	PE10 = (leds & 0x04) << 0x08; // LED2 - PE10
	 PE7 = (leds & 0x02) << 0x06; // LED1 - PE7
	 PE8 = (leds & 0x01) << 0x08; // LED0 - PE8

	GPIOB->ODR &= ~((1 << 10) + (1 << 11));
	GPIOB->ODR |= PB11 + PB10 ; // LEDs - PB11, PB10

	GPIOE->ODR &= ~((1 << 7) + (1 << 8) + (1 << 10) + (1 << 12) + (1 << 14) + (1 << 15));
	GPIOE->ODR |= PE15 + PE14 + PE12 + PE10 + PE7 + PE8 ; // LEDs - PE15, PE14, PE12, PE10, PE7, PE8

}

void GPIO_Init(void)
{
    // Configurar el puerto GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	(void)RCC->AHB1ENR;

    // Configurar PA7 como salida
    GPIOA->MODER &= ~(3 << (14)); // Limpiar los bits de modo para PA7
    GPIOA->MODER |=  (1 << (14));  // Config

	// Configurar el puerto GPIOB
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	(void)RCC->AHB1ENR;

	// LED1 - PB0 salida
	GPIOB->MODER &= ~(3);
	GPIOB->MODER |= (1);

    // DP7 - PB1 salida
	GPIOB->MODER &= ~(3 << (2)); // Limpiar los bits de modo para PB1
    GPIOB->MODER |= (1 << (2));  // Configurar PB1 como salida

    // SE4 - PB2 salida
	GPIOB->MODER &= ~(3 << (4)); // Limpiar los bits de modo para PB2
    GPIOB->MODER |= (1 << (4));  // Configurar PB2 como salida

    // SD3 - PB6 salida
	GPIOB->MODER &= ~(3 << (12)); // Limpiar los bits de modo para PB6
    GPIOB->MODER |= (1 << (12));  // Configurar PB6 como salida

    // LED2 - PB7 salida
	GPIOB->MODER &= ~(0x0000C000);
	GPIOB->MODER |= (0x00004000);

	// LED3 - PB14 salida
	GPIOB->MODER &= ~(0x30000000);
	GPIOB->MODER |= (0x10000000);

	// PB11 PB10
	// LED7 LED6
	GPIOB->MODER &= ~(3 << (22)); // Limpiar los bits de modo para PB11
	GPIOB->MODER |= (1 << (22));

	GPIOB->MODER &= ~(3 << (20)); // Limpiar los bits de modo para PB10
	GPIOB->MODER |= (1 << (20));

	// Configurar el puerto GPIOC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	(void)RCC->AHB1ENR;

    // SG6 - PC2 salida
    GPIOC->MODER &= ~(3 << (4)); // Limpiar los bits de modo para PC2
	GPIOC->MODER |= (1 << (4));

    // SW1 - PC13 Entrada
    // Configurar PC13 como entrada
    GPIOC->MODER &= ~(3 << (26)); // Limpiar los bits de modo para PC2
	GPIOC->MODER |= (0 << (26));


    // Configurar el puerto GPIOD
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	(void)RCC->AHB1ENR;

    // SA0 - PD11 salida
    // Configurar PD11 como salida
    GPIOD->MODER &= ~(3 << (22)); // Limpiar los bits de modo para PD11
	GPIOD->MODER |= (1 << (22));

	// SF5 - PD12 salida
    // Configurar PD12 como salida
    GPIOD->MODER &= ~(3 << (24)); // Limpiar los bits de modo para PD12
	GPIOD->MODER |= (1 << (24));

    // SB1 - PD13 salida
    // Configurar PD13 como salida
    GPIOD->MODER &= ~(3 << (26)); // Limpiar los bits de modo para PD13
	GPIOD->MODER |= (1 << (26));

     // D2 - PD14 salida
    // Configurar PD14 como salida
    GPIOD->MODER &= ~(3 << (28)); // Limpiar los bits de modo para PD14
	GPIOD->MODER |= (1 << (28));

    // D1 - PD15 salida
    // Configurar PD15 como salida
    GPIOD->MODER &= ~(3 << (30)); // Limpiar los bits de modo para PD15
	GPIOD->MODER |= (1 << (30));

	// Configurar el puerto GPIOE
	// PE15 PE14 PE13 PE12 PE11 PE10 PE9 PE8 PE7
	// LED5 LED4 SW4 LED3 SW2 LED2 SW1 LED0 LED1

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
	(void)RCC->AHB1ENR;

	//GPIOE->MODER &= ~(0xFFFFC000);
	//GPIOE->MODER |= (0x51514000);

	// Configurar PE15 como salida
	GPIOE->MODER &= ~(3 << (30));
	GPIOE->MODER |= (1 << (30));

	// Configurar PE14 como salida
	GPIOE->MODER &= ~(3 << (28));
	GPIOE->MODER |= (1 << (28));

	// Configurar PE13 como entrada
	GPIOE->MODER &= ~(3 << (26));
	GPIOE->MODER |= (0 << (26));

	// Configurar PE12 como salida
	GPIOE->MODER &= ~(3 << (24));
	GPIOE->MODER |= (1 << (24));

	// Configurar PE11 como entrada
	GPIOE->MODER &= ~(3 << (22));
	GPIOE->MODER |= (0 << (22));

	// Configurar PE10 como salida
	GPIOE->MODER &= ~(3 << (20));
	GPIOE->MODER |= (1 << (20));

	// Configurar PE9 como entrada
	GPIOE->MODER &= ~(3 << (18));
	GPIOE->MODER |= (0 << (18));

	// Configurar PE8 como salida
	GPIOE->MODER &= ~(3 << (16));
	GPIOE->MODER |= (1 << (16));

	// Configurar PE7 como salida
	GPIOE->MODER &= ~(3 << (14));
	GPIOE->MODER |= (1 << (14));

	// Configurar el puerto GPIOF
	// PF15 PF14 PF13
	// SW5 SW3 SW0

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
	(void)RCC->AHB1ENR;

    // SC2 Configurar PF4 como salida
	GPIOF->MODER &= ~(3 << (8));
	GPIOF->MODER |=  (1 << (8));

    // DO Configurar PF12 como salida
	GPIOF->MODER &= ~(3 << (24));
	GPIOF->MODER |=  (1 << (24));

	// Configurar PF13 como entrada
	GPIOF->MODER &= ~(3 << (26));
	GPIOF->MODER |= (0 << (26));

    // Configurar PF14 como entrada
	GPIOF->MODER &= ~(3 << (28));
	GPIOF->MODER |= (0 << (28));

    // Configurar PF15 como entrada
	GPIOF->MODER &= ~(3 << (30));
	GPIOF->MODER |= (0 << (30));

	// Configurar el puerto GPIOG
	// PG14 PG9
	// SW6  SW7

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;
	(void)RCC->AHB1ENR;

	// Configurar PG14 como entrada
	GPIOG->MODER &= ~(3 << (28));
	GPIOG->MODER |= (0 << (28));

	// Configurar PG9 como entrada
	GPIOG->MODER &= ~(3 << (18));
	GPIOG->MODER |= (0 << (18));

}

void SystemClock_Config(void)
{

	RCC->CR |= RCC_CR_HSION;
	while(!(RCC->CR & RCC_CR_HSIRDY));

	RCC->CFGR &= ~RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_HSI;
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);

}

void Delay(uint32_t count)
{
	volatile uint32_t i;

	for (i = 0; i < count; i++)
	{
		__NOP();
	}
}

