/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f429xx.h"

// Prototipos de funciones
void SystemClock_Config_HSI(void);
void GPIO_Init(void);
void Delay(uint32_t count);

int main(void)
{

    SystemClock_Config_HSI();
    GPIO_Init();

    while (1)
    {
       GPIOB->ODR ^= (1);
       Delay(500000);
    }
}

void GPIO_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

    GPIOB->MODER &= ~(3);
    GPIOB->MODER |=  (1);
}

void SystemClock_Config_HSI(void)
{
    RCC->CR |= RCC_CR_HSION;
    while(!(RCC->CR & RCC_CR_HSIRDY));

    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_HSI;
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);
}

void Delay(uint32_t count)
{
    volatile uint32_t i;
    for (i = 0; i < count; i++)
    {
        __NOP();
    }
}
