/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx_hal.h"

void SysTick_Handler(void)
{
	HAL_IncTick();
}


// Prototipos de funciones
void SystemClock_Config(void);
void GPIO_Init(void);
void salida_leds(uint8_t leds);
void salida_display(uint8_t display);
void board_leds(uint8_t leds);
uint8_t deco_display(uint8_t numero);
uint8_t entrada_sw(void);

int main(void)
{
  uint8_t leds_estado = 0;
  uint8_t contador = 0;
  uint32_t refresco = 0;

  // Inicialización del sistema
  HAL_Init();
  SystemClock_Config();
  GPIO_Init();

  while (1)
  {
    // 1. Control de LEDs de la placa mediante el Botón B1 (PC13)
    if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET)
    {
      leds_estado ^= 0x02;
      leds_estado &= ~(0x04);
      board_leds(leds_estado);
    }
    else
    {
      leds_estado ^= 0x04;
      leds_estado &= ~(0x02);
      board_leds(leds_estado);
    }

    // 2. Lectura de dip-switches y actualización de LEDs externos
    salida_leds(entrada_sw());

    // 3. Multiplexado Display - DÍGITO 0 (Decenas)
    HAL_GPIO_WritePin(GPIOF, GPIO_PIN_12, GPIO_PIN_SET);   // D0 ON
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET); // D1 OFF
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET); // D2 OFF
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,  GPIO_PIN_RESET); // D3 OFF

    salida_display(deco_display(contador / 10));
    HAL_Delay(5); // Retardo de multiplexado preciso de 5ms

    // 4. Multiplexado Display - DÍGITO 1 (Unidades)
    HAL_GPIO_WritePin(GPIOF, GPIO_PIN_12, GPIO_PIN_RESET); // D0 OFF
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);   // D1 ON
    HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET); // D2 OFF
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,  GPIO_PIN_RESET); // D3 OFF

    salida_display(deco_display(contador % 10));
    HAL_Delay(5); // Retardo de multiplexado preciso de 5ms

    // 5. Control de tiempo para el incremento del contador (~1 segundo)
    refresco++;
    if (refresco >= 100)
    {
    	leds_estado ^= 0x01;
    	board_leds(leds_estado);

    	contador++;
    	if (contador > 99)
    	{
    		contador = 0;
    	}
    	refresco = 0;
    }
  }
}

uint8_t deco_display(uint8_t numero)
{
  switch(numero)
  {
    case 0: return 0xBF; // 0
    case 1: return 0x86; // 1
    case 2: return 0xDB; // 2
    case 3: return 0xCF; // 3
    case 4: return 0xE6; // 4
    case 5: return 0xED; // 5
    case 6: return 0xFD; // 6
    case 7: return 0x87; // 7
    case 8: return 0xFF; // 8
    case 9: return 0xEF; // 9
    default: return 0x00;
  }
}

void salida_display(uint8_t display)
{
  // Mapeo bit a bit a pines GPIO usando HAL
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1,  (display & 0x80) ? GPIO_PIN_SET : GPIO_PIN_RESET); // DP
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_2,  (display & 0x40) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SG
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, (display & 0x20) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SF
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2,  (display & 0x10) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SE
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6,  (display & 0x08) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SD
  HAL_GPIO_WritePin(GPIOF, GPIO_PIN_4,  (display & 0x04) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SC
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, (display & 0x02) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SB
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_11, (display & 0x01) ? GPIO_PIN_SET : GPIO_PIN_RESET); // SA
}

uint8_t entrada_sw(void)
{
  uint8_t entrada = 0;

  // Lectura de pines y construcción de la máscara de bits
  if (HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_13) == GPIO_PIN_SET) entrada |= (1 << 0); // SW0
  if (HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_9)  == GPIO_PIN_SET) entrada |= (1 << 1); // SW1
  if (HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_11) == GPIO_PIN_SET) entrada |= (1 << 2); // SW2
  if (HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_14) == GPIO_PIN_SET) entrada |= (1 << 3); // SW3
  if (HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_13) == GPIO_PIN_SET) entrada |= (1 << 4); // SW4
  if (HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_15) == GPIO_PIN_SET) entrada |= (1 << 5); // SW5
  if (HAL_GPIO_ReadPin(GPIOG, GPIO_PIN_14) == GPIO_PIN_SET) entrada |= (1 << 6); // SW6
  if (HAL_GPIO_ReadPin(GPIOG, GPIO_PIN_9)  == GPIO_PIN_SET) entrada |= (1 << 7); // SW7

  return entrada;
}

void board_leds(uint8_t leds)
{
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0,  (leds & 0x01) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LD0 (Verde)
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7,  (leds & 0x02) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LD1 (Azul)
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, (leds & 0x04) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LD2 (Rojo)
}

void salida_leds(uint8_t leds)
{
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8,  (leds & 0x01) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED0
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_7,  (leds & 0x02) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED1
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_10, (leds & 0x04) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED2
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_12, (leds & 0x08) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED3
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_14, (leds & 0x10) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED4
  HAL_GPIO_WritePin(GPIOE, GPIO_PIN_15, (leds & 0x20) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED5
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, (leds & 0x40) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED6
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, (leds & 0x80) ? GPIO_PIN_SET : GPIO_PIN_RESET); // LED7
}

void GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  // 1. Habilitar relojes de todos los puertos GPIO utilizados
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOE_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOG_CLK_ENABLE();

  // 2. Configurar Salidas de Puerto A (PA7)
  GPIO_InitStruct.Pin = GPIO_PIN_7;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  // 3. Configurar Salidas de Puerto B (PB0, PB1, PB2, PB6, PB7, PB10, PB11, PB14)
  GPIO_InitStruct.Pin = GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_6 |
                        GPIO_PIN_7 | GPIO_PIN_10 | GPIO_PIN_11 | GPIO_PIN_14;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

  // 4. Configurar Puerto C: PC2 (Salida), PC13 (Entrada)
  GPIO_InitStruct.Pin = GPIO_PIN_2;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = GPIO_PIN_13;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

  // 5. Configurar Salidas de Puerto D (PD11, PD12, PD13, PD14, PD15)
  GPIO_InitStruct.Pin = GPIO_PIN_11 | GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

  // 6. Configurar Puerto E: Salidas (PE7, PE8, PE10, PE12, PE14, PE15), Entradas (PE9, PE11, PE13)
  GPIO_InitStruct.Pin = GPIO_PIN_7 | GPIO_PIN_8 | GPIO_PIN_10 | GPIO_PIN_12 | GPIO_PIN_14 | GPIO_PIN_15;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = GPIO_PIN_9 | GPIO_PIN_11 | GPIO_PIN_13;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

  // 7. Configurar Puerto F: Salidas (PF4, PF12), Entradas (PF13, PF14, PF15)
  GPIO_InitStruct.Pin = GPIO_PIN_4 | GPIO_PIN_12;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  HAL_GPIO_Init(GPIOF, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOF, &GPIO_InitStruct);

  // 8. Configurar Puerto G: Entradas (PG9, PG14)
  GPIO_InitStruct.Pin = GPIO_PIN_9 | GPIO_PIN_14;
  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(GPIOG, &GPIO_InitStruct);
}

void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  HAL_RCC_OscConfig(&RCC_OscInitStruct);

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                                RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0);
}
